# Generated by Django 5.0.6 on 2024-07-07 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import djaframe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "obj_model",
                    models.FileField(
                        max_length=200,
                        null=True,
                        upload_to=djaframe.models.entity_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["obj"]
                            )
                        ],
                        verbose_name="OBJ file",
                    ),
                ),
                (
                    "mtl_model",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to=djaframe.models.entity_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mtl"]
                            )
                        ],
                        verbose_name="MTL file",
                    ),
                ),
                (
                    "switch",
                    models.BooleanField(default=False, help_text="Switch Z/Y axis"),
                ),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=djaframe.models.material_image_directory_path
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_images",
                        to="djaframe.entity",
                        verbose_name="Material image",
                    ),
                ),
            ],
        ),
    ]
