# Generated by Django 5.0.6 on 2024-07-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0002_scene"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x_pos",
                    models.FloatField(
                        default=0,
                        help_text="Right is positive",
                        verbose_name="X position",
                    ),
                ),
                (
                    "z_pos",
                    models.FloatField(
                        default=0,
                        help_text="Back is positive",
                        verbose_name="Z position",
                    ),
                ),
                (
                    "rotation",
                    models.FloatField(
                        default=0,
                        help_text="Counterclockwise is positive",
                        verbose_name="Rotation",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="djaframe.entity",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="djaframe.scene",
                    ),
                ),
            ],
        ),
    ]
