# Generated by Django 5.0.7 on 2024-07-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0003_staging"),
    ]

    operations = [
        migrations.AddField(
            model_name="staging",
            name="position",
            field=models.CharField(
                default="0 0 0", help_text="L/R U/D I/O", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="staging",
            name="scale",
            field=models.CharField(
                default="1 1 1", help_text="Width Heigth Depth", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="staging",
            name="rotation",
            field=models.CharField(
                default="0 0 0", help_text="Pitch Yaw Roll", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="staging",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staged_entities",
                to="djaframe.scene",
            ),
        ),
    ]
