# Generated by Django 5.0.7 on 2024-07-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0004_staging_position_staging_scale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staging",
            name="x_pos",
        ),
        migrations.RemoveField(
            model_name="staging",
            name="z_pos",
        ),
    ]
