# Generated by Django 5.0.7 on 2024-07-14 15:37

import django.core.validators
from django.db import migrations, models

import djaframe.models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0006_scene_image_alter_staging_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="gltf_model",
            field=models.FileField(
                blank=True,
                help_text="Overrides all other entries",
                max_length=200,
                null=True,
                upload_to=djaframe.models.entity_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gltf", "glb"]
                    )
                ],
                verbose_name="GLTF file",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="obj_model",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=djaframe.models.entity_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["obj"]
                    )
                ],
                verbose_name="OBJ file",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Equirectangular image",
                null=True,
                upload_to="uploads/djaframe/scene/",
            ),
        ),
    ]
