# Generated by Django 5.0.7 on 2024-07-17 17:08

import django.core.validators
from django.db import migrations, models

import djaframe.models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0007_entity_gltf_model_alter_entity_obj_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DxfScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "dxf",
                    models.FileField(
                        help_text="Please, transform 3DSolids into Meshes before upload",  # noqa
                        max_length=200,
                        upload_to=djaframe.models.entity_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
            ],
        ),
    ]
