# Generated by Django 5.0.7 on 2024-07-17 17:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import djaframe.models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0008_dxfscene"),
    ]

    operations = [
        migrations.CreateModel(
            name="DxfObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj",
                    models.FileField(
                        max_length=200,
                        upload_to=djaframe.models.entity_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["obj"]
                            )
                        ],
                    ),
                ),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dxf_objects",
                        to="djaframe.dxfscene",
                    ),
                ),
            ],
        ),
    ]
