# Generated by Django 5.0.7 on 2024-08-14 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0009_dxfobject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dxfscene",
            options={"verbose_name": "DXF Scene", "verbose_name_plural": "DXF Scenes"},
        ),
        migrations.AddField(
            model_name="scene",
            name="dxf",
            field=models.FileField(
                blank=True,
                help_text="Please, transform 3DSolids into Meshes before upload",
                max_length=200,
                null=True,
                upload_to="uploads/djaframe/scene/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["dxf"]
                    )
                ],
                verbose_name="DXF file",
            ),
        ),
        migrations.AlterField(
            model_name="dxfobject",
            name="obj",
            field=models.FileField(
                max_length=200,
                upload_to="uploads/djaframe/dxf-scene/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["obj"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dxfscene",
            name="dxf",
            field=models.FileField(
                help_text="Please, transform 3DSolids into Meshes before upload",
                max_length=200,
                upload_to="uploads/djaframe/dxf-scene/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["dxf"]
                    )
                ],
                verbose_name="DXF file",
            ),
        ),
    ]
