# Generated by Django 5.0.7 on 2024-08-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "djaframe",
            "0010_alter_dxfscene_options_scene_dxf_alter_dxfobject_obj_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DxfObject",
        ),
        migrations.DeleteModel(
            name="DxfScene",
        ),
    ]
