# Generated by Django 5.0.7 on 2024-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0011_delete_dxfobject_delete_dxfscene"),
    ]

    operations = [
        migrations.AddField(
            model_name="staging",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="staging",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
