# Generated by Django 5.0.7 on 2024-08-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djaframe", "0012_staging_color_staging_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="color",
        ),
    ]
