# Generated by Django 5.0.6 on 2024-06-29 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="mtl_model",
            field=models.FileField(
                default="uploads/aframe/obj/sirena.mtl",
                max_length=200,
                upload_to="uploads/aframe/obj/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mtl"]
                    )
                ],
                verbose_name="MTL file",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entity",
            name="obj_model",
            field=models.FileField(
                max_length=200,
                upload_to="uploads/aframe/obj/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["obj"]
                    )
                ],
                verbose_name="OBJ file",
            ),
        ),
    ]
