# Generated by Django 5.0.6 on 2024-06-29 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_entity_mtl_model_alter_entity_obj_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="switch",
            field=models.BooleanField(default=False, help_text="Switch Z/Y axis"),
        ),
        migrations.AddField(
            model_name="entity",
            name="title",
            field=models.CharField(default="Title", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entity",
            name="mtl_model",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="uploads/aframe/obj/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mtl"]
                    )
                ],
                verbose_name="MTL file",
            ),
        ),
    ]
