# Generated by Django 5.0.6 on 2024-07-05 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import entities.models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_entity_description_entity_switch_entity_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AlterField(
            model_name="entity",
            name="mtl_model",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=entities.models.entity_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mtl"]
                    )
                ],
                verbose_name="MTL file",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="obj_model",
            field=models.FileField(
                max_length=200,
                null=True,
                upload_to=entities.models.entity_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["obj"]
                    )
                ],
                verbose_name="OBJ file",
            ),
        ),
        migrations.CreateModel(
            name="MaterialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=entities.models.material_image_directory_path
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_image",
                        to="entities.entity",
                        verbose_name="Material image",
                    ),
                ),
            ],
        ),
    ]
